import { findIndex } from "lodash";

export interface IVietnamCity {
  id: number;
  name: string;
  slug: string;
}

export function getVietnamCityByName(name: string) {
  const idx = findIndex(vietnamCities, (city) => name === city.name);
  return vietnamCities[idx];
}

export const vietnamCities: IVietnamCity[] = [
  { id: 1, name: "Bà Rịa", slug: "bà-rịa" },
  { id: 2, name: "Bạc Liêu", slug: "bạc-liêu" },
  { id: 3, name: "Bảo Lộc", slug: "bảo-lộc" },
  { id: 4, name: "Bắc Giang", slug: "bắc-giang" },
  { id: 5, name: "Bắc Kạn", slug: "bắc-kạn" },
  { id: 6, name: "Bắc Ninh", slug: "bắc-ninh" },
  { id: 7, name: "Biên Hòa", slug: "biên-hòa" },
  { id: 8, name: "Bến Tre", slug: "bến-tre" },
  { id: 9, name: "Bình Dương", slug: "bình-dương" },
  { id: 9, name: "Buôn Ma Thuột", slug: "buôn-ma-thuột" },
  { id: 10, name: "Cẩm Phả", slug: "cẩm-phả" },
  { id: 11, name: "Cà Mau", slug: "cà-mau" },
  { id: 12, name: "Cam Ranh", slug: "cam-ranh" },
  { id: 13, name: "Cao Bằng", slug: "cao-bằng" },
  { id: 14, name: "Cao Lãnh", slug: "cao-lãnh" },
  { id: 15, name: "Châu Đốc", slug: "châu-đốc" },
  { id: 16, name: "Chí Linh", slug: "chí-linh" },
  { id: 17, name: "Dĩ An", slug: "dĩ-an" },
  { id: 18, name: "Đà Lạt", slug: "đà-lạt" },
  { id: 19, name: "Điện Biên Phủ", slug: "điện-biên-phủ" },
  { id: 20, name: "Đông Hà", slug: "đông-hà" },
  { id: 21, name: "Đồng Hới", slug: "đồng-hới" },
  { id: 22, name: "Đồng Xoài", slug: "đồng-xoài" },
  { id: 23, name: "Gia Nghĩa", slug: "gia-nghĩa" },
  { id: 24, name: "Hà Giang", slug: "hà-giang" },
  { id: 25, name: "Hà Tiên", slug: "hà-tiên" },
  { id: 26, name: "Hà Tĩnh", slug: "hà-tĩnh" },
  { id: 27, name: "Hạ Long", slug: "hạ-long" },
  { id: 28, name: "Hải Dương", slug: "hải-dương" },
  { id: 29, name: "Hòa Bình", slug: "hòa-bình" },
  { id: 30, name: "Hồ Chí Minh", slug: "hồ-chí-minh" },
  { id: 30, name: "Hội An", slug: "hội-an" },
  { id: 31, name: "Huế", slug: "huế" },
  { id: 32, name: "Hưng Yên", slug: "hưng-yên" },
  { id: 33, name: "Kon Tum", slug: "kon-tum" },
  { id: 34, name: "Lai Châu", slug: "lai-châu" },
  { id: 35, name: "Lạng Sơn", slug: "lạng-sơn" },
  { id: 36, name: "Lào Cai", slug: "lào-cai" },
  { id: 37, name: "Long Khánh", slug: "long-khánh" },
  { id: 38, name: "Long Xuyên", slug: "long-xuyên" },
  { id: 39, name: "Móng Cái", slug: "móng-cái" },
  { id: 40, name: "Mỹ Tho", slug: "mỹ-tho" },
  { id: 41, name: "Nam Định", slug: "nam-định" },
  { id: 42, name: "Ngã Bảy", slug: "ngã-bảy" },
  { id: 43, name: "Nha Trang", slug: "nha-trang" },
  { id: 44, name: "Ninh Bình", slug: "ninh-bình" },
  { id: 45, name: "Phan Rang–Tháp Chàm", slug: "phan-rang–tháp-chàm" },
  { id: 46, name: "Phan Thiết", slug: "phan-thiết" },
  { id: 47, name: "Phủ Lý", slug: "phủ-lý" },
  { id: 48, name: "Phúc Yên", slug: "phúc-yên" },
  { id: 49, name: "Pleiku", slug: "pleiku" },
  { id: 50, name: "Quảng Ngãi", slug: "quảng-ngãi" },
  { id: 51, name: "Quy Nhơn", slug: "quy-nhơn" },
  { id: 52, name: "Rạch Giá", slug: "rạch-giá" },
  { id: 53, name: "Sa Đéc", slug: "sa-đéc" },
  { id: 54, name: "Sầm Sơn", slug: "sầm-sơn" },
  { id: 55, name: "Sóc Trăng", slug: "sóc-trăng" },
  { id: 56, name: "Sơn La", slug: "sơn-la" },
  { id: 57, name: "Sông Công", slug: "sông-công" },
  { id: 58, name: "Tam Điệp", slug: "tam-điệp" },
  { id: 59, name: "Tam Kỳ", slug: "tam-kỳ" },
  { id: 60, name: "Tân An", slug: "tân-an" },
  { id: 61, name: "Tây Ninh", slug: "tây-ninh" },
  { id: 62, name: "Thái Bình", slug: "thái-bình" },
  { id: 63, name: "Thái Nguyên", slug: "thái-nguyên" },
  { id: 64, name: "Thanh Hóa", slug: "thanh-hóa" },
  { id: 65, name: "Thủ Dầu Một", slug: "thủ-dầu một" },
  { id: 66, name: "Thuận An", slug: "thuận-an" },
  { id: 67, name: "Trà Vinh", slug: "trà-vinh" },
  { id: 68, name: "Tuy Hòa", slug: "tuy-hòa" },
  { id: 69, name: "Tuyên Quang", slug: "tuyên-quang" },
  { id: 70, name: "Uông Bí", slug: "uông-bí" },
  { id: 71, name: "Vị Thanh", slug: "vị-thanh" },
  { id: 72, name: "Việt Trì", slug: "việt-trì" },
  { id: 73, name: "Vinh", slug: "vinh" },
  { id: 74, name: "Vĩnh Long", slug: "vĩnh-long" },
  { id: 75, name: "Vĩnh Yên", slug: "vĩnh-yên" },
  { id: 76, name: "Vũng Tàu", slug: "vũng-tàu" },
  { id: 77, name: "Yên Bái", slug: "yên-bái" },
];
