import { findIndex } from "lodash";

export interface IVietnamCity {
  name: string;
}

export function getVietnamCityByName(name: string) {
  const idx = findIndex(vietnamProvinces, (city) => name === city.name);
  return vietnamProvinces[idx];
}

export const vietnamProvinces: IVietnamCity[] = [
  { name: "An Giang" },
  { name: "Kon Tum" },
  { name: "Bà Rịa – Vũng Tàu" },
  { name: "Lai Châu" },
  { name: "Bắc Giang" },
  { name: "Lâm Đồng" },
  { name: "Bắc Kạn" },
  { name: "Lạng Sơn" },
  { name: "Bạc Liêu" },
  { name: "Lào Cai" },
  { name: "Bắc Ninh" },
  { name: "Long An" },
  { name: "Bến Tre" },
  { name: "Nam Định" },
  { name: "Bình Định" },
  { name: "Nghệ An" },
  { name: "Bình Dương" },
  { name: "Ninh Bình" },
  { name: "Bình Phước" },
  { name: "Ninh Thuận" },
  { name: "Bình Thuận" },
  { name: "Phú Thọ" },
  { name: "Cà Mau" },
  { name: "Phú Yên" },
  { name: "Cần Thơ" },
  { name: "Quảng Bình" },
  { name: "Cao Bằng" },
  { name: "Quảng Nam" },
  { name: "Đà Nẵng" },
  { name: "Quảng Ngãi" },
  { name: "Đắk Lắk" },
  { name: "Quảng Ninh" },
  { name: "Đắk Nông" },
  { name: "Quảng Trị" },
  { name: "Điện Biên" },
  { name: "Sóc Trăng" },
  { name: "Đồng Nai" },
  { name: "Sơn La" },
  { name: "Đồng Tháp" },
  { name: "Tây Ninh" },
  { name: "Gia Lai" },
  { name: "Thái Bình" },
  { name: "Hà Giang" },
  { name: "Thái Nguyên" },
  { name: "Hà Nam" },
  { name: "Thanh Hóa" },
  { name: "Hà Nội" },
  { name: "Thừa Thiên Huế" },
  { name: "Hà Tĩnh" },
  { name: "Tiền Giang" },
  { name: "Hải Dương" },
  { name: "TP Hồ Chí Minh" },
  { name: "Hải Phòng" },
  { name: "Trà Vinh" },
  { name: "Hậu Giang" },
  { name: "Tuyên Quang" },
  { name: "Hòa Bình" },
  { name: "Vĩnh Long" },
  { name: "Hưng Yên" },
  { name: "Vĩnh Phúc" },
  { name: "Khánh Hòa" },
  { name: "Yên Bái" },
  { name: "Kiên Giang" },
];
