AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  DBUsername:
    Type: String
  DBName:
    Type: String
  DBPassword:
    Type: String
  VpcId:
    Type: String
Resources:
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: prod-sdconnect-rds-tg
      GroupDescription: Security group for NGINX container
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  ProdDbInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      Engine: MySQL
      EngineVersion: 8.0.23
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - "sg-04b96fc32bc97ea4f"
        - !GetAtt RDSSecurityGroup.GroupId
Outputs:
  InstanceId:
    Value:
      !Join [
        ".",
        [!Ref ProdDbInstance, "ctv7foikp0a0.ap-southeast-1.rds.amazonaws.com"],
      ]
    Description: InstanceId of the newly created RDS Instance
