AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  DBUsername:
    Type: String
  DBPassword:
    Type: String
  VpcId:
    Type: String
Resources:
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: dev-sdconnect-chat-rds-security-group
      GroupDescription: Security group for NGINX container
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
  DevDbInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      # DBName: !Ref DBName
      DBInstanceClass: db.t2.micro
      AllocatedStorage: 20
      Engine: MySQL
      EngineVersion: 8.0.16
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - "sg-04b96fc32bc97ea4f"
        - !GetAtt RDSSecurityGroup.GroupId
Outputs:
  InstanceId:
    Value:
      !Join [
        ".",
        [!Ref DevDbInstance, "ctv7foikp0a0.ap-southeast-1.rds.amazonaws.com"],
      ]
    Description: InstanceId of the newly created RDS Instance
