AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ElasticacheSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Elasticache Security Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: 0.0.0.0/0
  ProdSdconnectRedis:
    Type: 'AWS::ElastiCache::CacheCluster'
    Properties:
      Engine: redis
      CacheNodeType: cache.t2.micro
      NumCacheNodes: '1'
      VpcSecurityGroupIds:
        - !GetAtt ElasticacheSecurityGroup.GroupId
Outputs:
  InstanceId:
    Description: Instance of the newly created redis
    Value: !Ref ProdSdconnectRedis
  Address:
    Description: ElastiCache endpoint address
    Value: !GetAtt ProdSdconnectRedis.RedisEndpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}-Address
  Port:
    Description: ElastiCache endpoint port
    Value: !GetAtt ProdSdconnectRedis.RedisEndpoint.Port
    Export:
      Name: !Sub ${AWS::StackName}-Port