AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SubnetID:
    Type: String
  DockerImageURI:
    Type: String
  PORT:
    Type: Number
  NODE_ENV:
    Type: String
  JWT_SECRET:
    Type: String
  DEV_DB_DIALECT:
    Type: String
  DEV_DB_HOST:
    Type: String
  DEV_DB_DATABASE:
    Type: String
  DEV_DB_PORT:
    Type: String
  DEV_DB_USERNAME:
    Type: String
  DEV_DB_PASSWORD:
    Type: String
  AWS_REGION:
    Type: String
  DEV_AWS_ACCESS_KEY:
    Type: String
  DEV_AWS_SECRET_KEY:
    Type: String
  DEV_S3_BUCKET_NAME:
    Type: String
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: sdconnect-cluster
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: sdconnect-logs
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: sdconnect-cf-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ContainerSecurityGroup
      GroupDescription: Security group for NGINX container
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: sdconnect-dev-api-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: sdconnect-dev-api
          Image: !Ref DockerImageURI
          PortMappings:
            - ContainerPort: !Ref PORT
          Environment:
            - Name: PORT
              Value: !Ref PORT
            - Name: NODE_ENV
              Value: !Ref NODE_ENV
            - Name: JWT_SECRET
              Value: !Ref JWT_SECRET
            - Name: DEV_DB_DIALECT
              Value: !Ref DEV_DB_DIALECT
            - Name: DEV_DB_HOST
              Value: !Ref DEV_DB_HOST
            - Name: DEV_DB_DATABASE
              Value: !Ref DEV_DB_DATABASE
            - Name: DEV_DB_PORT
              Value: !Ref DEV_DB_PORT
            - Name: DEV_DB_USERNAME
              Value: !Ref DEV_DB_USERNAME
            - Name: DEV_DB_PASSWORD
              Value: !Ref DEV_DB_PASSWORD
            - Name: AWS_REGION
              Value: !Ref AWS_REGION
            - Name: DEV_AWS_ACCESS_KEY
              Value: !Ref DEV_AWS_ACCESS_KEY
            - Name: DEV_AWS_SECRET_KEY
              Value: !Ref DEV_AWS_SECRET_KEY
            - Name: DEV_S3_BUCKET_NAME
              Value: !Ref DEV_S3_BUCKET_NAME
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
      RequiresCompatibilities:
        - FARGATE
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: sdconnect-dev-api-ecs
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetID
          SecurityGroups:
            - !GetAtt ContainerSecurityGroup.GroupId
