AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  SubnetID:
    Type: String
  DockerImageURI:
    Type: String
  PORT:
    Type: Number
  NodeEnv:
    Type: String
  JwtSecret:
    Type: String
  DevDBDialect:
    Type: String
  DevDBHost:
    Type: String
  DevDBDatabase:
    Type: String
  DevDBPort:
    Type: String
  DevDBUsername:
    Type: String
  DevDBPassword:
    Type: String
  AwsRegion:
    Type: String
  DevAWSAccessKey:
    Type: String
  DevAWSSecretKey:
    Type: String
  DevS3BucketName:
    Type: String
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: sdconnect-cluster
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: sdconnect-logs
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: sdconnect-cf-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ContainerSecurityGroup
      GroupDescription: Security group for NGINX container
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: sdconnect-dev-api-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: sdconnect-dev-api
          Image: !Ref DockerImageURI
          PortMappings:
            - ContainerPort: !Ref PORT
          Environment:
            - Name: PORT
              Value: !Ref PORT
            - Name: NODE_ENV
              Value: !Ref NodeEnv
            - Name: JWT_SECRET
              Value: !Ref JwtSecret
            - Name: DEV_DB_DIALECT
              Value: !Ref DevDBDialect
            - Name: DEV_DB_HOST
              Value: !Ref DevDBHost
            - Name: DEV_DB_DATABASE
              Value: !Ref DevDBDatabase
            - Name: DEV_DB_PORT
              Value: !Ref DevDBPort
            - Name: DEV_DB_USERNAME
              Value: !Ref DevDBUsername
            - Name: DEV_DB_PASSWORD
              Value: !Ref DevDBPassword
            - Name: AWS_REGION
              Value: !Ref AwsRegion
            - Name: DEV_AWS_ACCESS_KEY
              Value: !Ref DevAWSAccessKey
            - Name: DEV_AWS_SECRET_KEY
              Value: !Ref DevAWSSecretKey
            - Name: DEV_S3_BUCKET_NAME
              Value: !Ref DevS3BucketName
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
      RequiresCompatibilities:
        - FARGATE
  Service:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: sdconnect-dev-api-ecs
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetID
          SecurityGroups:
            - !GetAtt ContainerSecurityGroup.GroupId
