AWSTemplateFormatVersion: 2010-09-09
Parameters:
  SubnetID:
    Type: String
    Default: 'subnet-9920bcc0'
  SubnetID2:
    Type: String
    Default: 'subnet-55bb1b33'
  SubnetID3:
    Type: String
    Default: 'subnet-a86fbee0'
  Vpc:
    Type: String
  Certificate:
    Type: String
  PORT:
    Type: Number
Resources:
  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      VpcId: !Ref Vpc
      GroupName: SDConnectAPIDevSG
      GroupDescription: Attached to the load balancer of the SDConnect api on DEV
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: !Ref PORT
          CidrIp: 0.0.0.0/0
  ELB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      IpAddressType: ipv4
      Name: sdconnect-api-elb
      Scheme: internet-facing
      SecurityGroups:
        - !Ref SecurityGroup
      Subnets:
        - !Ref SubnetID
        - !Ref SubnetID2
        - !Ref SubnetID3
      Type: application
  ELBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      Name: sdconnect-api-dev-elb-tg
      VpcId: !Ref Vpc
      HealthCheckEnabled: 'true'
      HealthCheckPath: /login
      HealthCheckProtocol: HTTP
      Protocol: HTTP
      Port: 80
      TargetType: ip
  ELBHTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref ELBTargetGroup
                Weight: 1
      LoadBalancerArn: !Ref ELB
      Port: 80
      Protocol: HTTP
  ELBHTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      SslPolicy: ELBSecurityPolicy-2016-08
      Certificates:
        - CertificateArn: !Ref Certificate
      DefaultActions:
        - Type: forward
          ForwardConfig:
            TargetGroups:
              - TargetGroupArn: !Ref ELBTargetGroup
                Weight: 1
      LoadBalancerArn: !Ref ELB
      Port: 443
      Protocol: HTTPS
Outputs:
  LoadBalancer:
    Description: 'The ELB name for the load balancer'
    Value: !Ref ELB
    Export:
      Name: !Sub '${AWS::StackName}-ELB'
  TargetGroup:
    Description: 'The ELB Target Group'
    Value: !Ref ELBTargetGroup
    Export:
      Name: !Sub '${AWS::StackName}-ELBTargetGroup'