import { findIndex } from "lodash";

export function getLocationByName(name: string) {
  const idx = findIndex(vietnamCities, (vc) => vc.name === name);
  return vietnamCities[idx];
}

export interface IVietnamCity {
  id: number;
  name: string;
}

export const vietnamCities: IVietnamCity[] = [
  { id: 1, name: "Bà Rịa" },
  { id: 2, name: "Bạc Liêu" },
  { id: 3, name: "Bảo Lộc" },
  { id: 4, name: "Bắc Giang" },
  { id: 5, name: "Bắc Kạn" },
  { id: 6, name: "Bắc Ninh" },
  { id: 7, name: "Biên Hòa" },
  { id: 8, name: "Bến Tre" },
  { id: 9, name: "Buôn Ma Thuột" },
  { id: 10, name: "Cẩm Phả" },
  { id: 11, name: "Cà Mau" },
  { id: 12, name: "Cam Ranh" },
  { id: 13, name: "Cao Bằng" },
  { id: 14, name: "Cao Lãnh" },
  { id: 15, name: "Châu Đốc" },
  { id: 16, name: "Chí Linh" },
  { id: 17, name: "Dĩ An" },
  { id: 18, name: "Đà Lạt" },
  { id: 19, name: "Điện Biên Phủ" },
  { id: 20, name: "Đông Hà" },
  { id: 21, name: "Đồng Hới" },
  { id: 22, name: "Đồng Xoài" },
  { id: 23, name: "Gia Nghĩa" },
  { id: 24, name: "Hà Giang" },
  { id: 25, name: "Hà Tiên" },
  { id: 26, name: "Hà Tĩnh" },
  { id: 27, name: "Hạ Long" },
  { id: 28, name: "Hải Dương" },
  { id: 29, name: "Hòa Bình" },
  { id: 30, name: "Hội An" },
  { id: 31, name: "Huế" },
  { id: 32, name: "Hưng Yên" },
  { id: 33, name: "Kon Tum" },
  { id: 34, name: "Lai Châu" },
  { id: 35, name: "Lạng Sơn" },
  { id: 36, name: "Lào Cai" },
  { id: 37, name: "Long Khánh" },
  { id: 38, name: "Long Xuyên" },
  { id: 39, name: "Móng Cái" },
  { id: 40, name: "Mỹ Tho" },
  { id: 41, name: "Nam Định" },
  { id: 42, name: "Ngã Bảy" },
  { id: 43, name: "Nha Trang" },
  { id: 44, name: "Ninh Bình" },
  { id: 45, name: "Phan Rang–Tháp Chàm" },
  { id: 46, name: "Phan Thiết" },
  { id: 47, name: "Phủ Lý" },
  { id: 48, name: "Phúc Yên" },
  { id: 49, name: "Pleiku" },
  { id: 50, name: "Quảng Ngãi" },
  { id: 51, name: "Quy Nhơn" },
  { id: 52, name: "Rạch Giá" },
  { id: 53, name: "Sa Đéc" },
  { id: 54, name: "Sầm Sơn" },
  { id: 55, name: "Sóc Trăng" },
  { id: 56, name: "Sơn La" },
  { id: 57, name: "Sông Công" },
  { id: 58, name: "Tam Điệp" },
  { id: 59, name: "Tam Kỳ" },
  { id: 60, name: "Tân An" },
  { id: 61, name: "Tây Ninh" },
  { id: 62, name: "Thái Bình" },
  { id: 63, name: "Thái Nguyên" },
  { id: 64, name: "Thanh Hóa" },
  { id: 65, name: "Thủ Dầu Một" },
  { id: 66, name: "Thuận An" },
  { id: 67, name: "Trà Vinh" },
  { id: 68, name: "Tuy Hòa" },
  { id: 69, name: "Tuyên Quang" },
  { id: 70, name: "Uông Bí" },
  { id: 71, name: "Vị Thanh" },
  { id: 72, name: "Việt Trì" },
  { id: 73, name: "Vinh" },
  { id: 74, name: "Vĩnh Long" },
  { id: 75, name: "Vĩnh Yên" },
  { id: 76, name: "Vũng Tàu" },
  { id: 77, name: "Yên Bái" },
];
