INSERT INTO `categories` (`id`, `nameVn`, `nameEn`, `industryId`) VALUES
-- 1st category: Business Services.
(1, "Tư vấn doanh nghiệp", "Business Consultation", 1),
(2, "Phần mềm quản lý", "Management Software", 1),
(3, "Thiết bị văn phòng", "Office stationaries", 1),
(4, "Tư vấn tài chính", "Financial Consultation", 1),
(5, "Dịch vụ kế toán", "Accouting Service", 1),
(6, "Luật kinh doanh", "Business Laws", 1),
(7, "Dịch vụ tín dụng", "Credits loan services", 1),
(8, "Tuyển dụng", "Recruitment", 1),
(9, "Dịch vụ ngân hàng", "Banking services", 1),
(10, "Phiên dịch", "Translation services", 1),
(11, "BH phi nhân thọ", "Non-life insurances", 1),
(12, "Bảo hiểm y tế", "Medical insurances", 1),

-- 2nd category: Events.
(13, "Truyền thông", "Media services", 2),
(14, "Tổ chức sự kiện", "Event management", 2),
(15, "Nhà hàng / KS", "Hotels & Restaurants", 2),
(16, "Du lịch", "Tourism", 2),
(17, "Rượu và đồ uống", "Wine & Beverages", 2),
(18, "Quà tặng", "Gifts", 2),
(19, "Hoa tươi", "Flowers", 2),
(20, "Trang trí", "Decorations", 2),
(21, "Bánh ngọt", "Cakes & Pastries", 2),
(22, "Chụp ảnh sự kiện", "Photography services", 2),
(23, "Triển lãm", "Exhibition", 2),

-- 3rd category: Marketing.
(24, "Thiết kế website", "Web Design & Development", 3),
(25, "Tư vấn thương hiệu", "Brand Development", 3),
(26, "Tư vấn chiến lược", "Strategic Consultation", 3),
(27, "Truyền thông", "Media services", 3),
(28, "Thiết kế", "Graphics Design", 3),
(29, "Quay phim", "Videography", 3),
(30, "Quảng cáo Radio", "Radio advertising", 3),
(31, "Quà tặng sự kiện", "Gifts for Events", 3),
(32, "In ấn", "Printing", 3),
(33, "Digital Marketing", "Digital Marketing", 3),
(34, "Content", "Content", 3),
(35, "Bảng Q/C", "Billboards", 3),

-- 4th category: Industrial-zone real-estate.
(36, "Mua - Bán - Thuê nhà xưởng", "Buy - Sell - Hire factories", 4),
(37, "Thẩm định giá BĐS", "Real-estate valuation", 4),
(38, "Quản lý tài sản nhà xưởng", "Factory assets management", 4),
(39, "Bảo hiểm", "Insurances", 4),
(40, "Dịch vụ pháp lý", "Legal services", 4),
(41, "VP công chứng", "Notary services", 4),
(42, "Quản lý BĐS công nghiệp", "Industrial real-estate management", 4),
(43, "DV bảo vệ an ninh", "Security services", 4),
(44, "DV nhà ở công nhân", "Workers' accomodations", 4);
