INSERT INTO `industries` (`id`, `nameVn`, `nameEn`) VALUES
(1, 'Hỗ trợ doanh nghiệp', 'Business Services'),
(2, 'Sự kiện', 'Events'),
(3, 'Marketing', 'Marketing'),
(4, 'BĐS KCN', 'Industrial-zone real-estate'),
(5, 'Xây Dựng', 'Construction'),
(6, 'Thiết bị an ninh an toàn', 'Security & Safety equipments'),
(7, 'Nhiên liệu', 'Fuel'),
(8, 'Nguyên liệu', 'Material'),
(9, 'Phụ liệu may mặc', 'Garment accessories'),
(10, 'Phụ liệu dày gia', 'Footwear accessories'),
(11, 'Linh kiện điện tử', 'Electronic accessories'),
(12, 'Nguyên phụ liệu cơ khí', 'Mechanical materials & accessories'),
(13, 'Phụ liệu Ngành nhựa', 'Plastic accessories'),
(14, 'Nguyên liệu ngành Nông sản', 'Agricultural materials'),
(15, 'Dụng cụ vật tư cơ khí', 'Mechanical tools'),
(16, 'Thiết bị VPP và bảo hộ LĐ', 'Office stationaries and safety equipments'),
(17, 'Nội thất văn phòng', 'Office furnitures'),
(18, 'Thiết bị vật tư Điện nước nhẹ', 'Water-&-Electricity tools'),
(19, 'Logistics', 'Logistics'),
(20, 'Hoá chất', 'Chemicals'),
(21, 'DV chăm sóc cảnh quan', 'Botany Service'),
(22, 'Sức khoẻ - Y tế', 'Health - Medicine');