#schema: "http://localhost:8080/graphql"
schema: "https://api.dev.sdconnect.vn/graphql"
documents: "**/*.graphql"
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDIr: __generated__
